default_context:
  project_name: 'crater'
  project_slug: 'crater'
  domain_main: 'maksimov.ski'
  domain_staging: 'stag.maksimov.ski'
  docker_swarm_stack_name_main: 'maksimov-ski'
  docker_swarm_stack_name_staging: 'stag-maksimov-ski'
  secret_key: '89D6EF82BB3FDC9727DA1B14CBE1E'
  first_superuser: 'goran@maksimov.ski'
  first_superuser_password: '123456'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.maksimov.ski", "https://stag.maksimov.ski", "https://maksimov.ski", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@maksimov.ski'
  postgres_password: '123456'
  pgadmin_default_user: 'crater'
  pgadmin_default_user_password: '123456'
  traefik_constraint_tag: 'maksimov.ski'
  traefik_constraint_tag_staging: 'stag.maksimov.ski'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
